server:
  port: 9090

  application:
    version: 0.1
    title: API-ESCOLA

  spring:

    datasource:
      url: "jdbc:h2:file:./data/escola_db"
      username: "sa"
      password: ""
      driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: "/h2-console"